search_input_graph_path: s3a://qfrag/graphs/citeseer.unsafe.graph
search_output_path: output-search
search_injective: true
search_outliers_pct: 0.1
search_outliers_min_matches: 0
search_fastNeighbors: true
search_write_in_binary: false
system_type: search
log_level: fatal
search_query_graph_path: s3a://qfrag/queries/Q1-citeseer
search_output_active: true
search_num_vertices: 3312
search_num_edges: 9072
search_num_labels: 6
data_partitions_dir: data/partitions
partition_path: s3a://qfrag/partitioned_graph/
